"""Remove close

Revision ID: 7025efefbf30
Revises: 5ede1c57531f
Create Date: 2022-06-01 12:28:57.576361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7025efefbf30'
down_revision = '5ede1c57531f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_orders', 'closed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_orders', sa.Column('closed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
