"""Initial

Revision ID: 82b9511cb7b8
Revises: 
Create Date: 2022-05-07 18:08:03.408244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b9511cb7b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk__user')),
    sa.UniqueConstraint('chat_id', name=op.f('uq__user__chat_id')),
    sa.UniqueConstraint('username', name=op.f('uq__user__username'))
    )
    op.create_table('order',
    sa.Column('order_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('number_of_person', sa.String(length=100), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.Column('transfer', sa.String(length=100), nullable=False),
    sa.Column('insurance', sa.String(length=100), nullable=False),
    sa.Column('excursion', sa.String(length=100), nullable=False),
    sa.Column('wishes', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.chat_id'], name=op.f('fk__order__user_id__user')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk__order')),
    sa.UniqueConstraint('order_id', name=op.f('uq__order__order_id'))
    )
    op.create_table('user_orders',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], name=op.f('fk__user_orders__order_id__order')),
    sa.ForeignKeyConstraint(['user_id'], ['user.chat_id'], name=op.f('fk__user_orders__user_id__user')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk__user_orders')),
    sa.UniqueConstraint('order_id', name=op.f('uq__user_orders__order_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_orders')
    op.drop_table('order')
    op.drop_table('user')
    # ### end Alembic commands ###
