"""Add create profile date

Revision ID: 8b1da4ce6dbf
Revises: 7025efefbf30
Create Date: 2022-08-04 14:20:05.239113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1da4ce6dbf'
down_revision = '7025efefbf30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('register_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'register_date')
    # ### end Alembic commands ###
