"""Change order model

Revision ID: aa980d94ee32
Revises: cbeaa7516401
Create Date: 2022-05-24 22:28:39.024620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa980d94ee32'
down_revision = 'cbeaa7516401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('about_order', sa.Text(), nullable=False))
    op.add_column('order', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_column('order', 'excursion')
    op.drop_column('order', 'wishes')
    op.drop_column('order', 'transfer')
    op.drop_column('order', 'number_of_person')
    op.drop_column('order', 'insurance')
    op.drop_column('order', 'duration')
    op.drop_column('order', 'place')
    op.drop_column('order', 'time')
    op.add_column('user_orders', sa.Column('manager_id', sa.BigInteger(), nullable=False))
    op.add_column('user_orders', sa.Column('close_date', sa.DateTime(), nullable=False))
    op.drop_constraint('fk__user_orders__user_id__user', 'user_orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk__user_orders__manager_id__user'), 'user_orders', 'user', ['manager_id'], ['chat_id'])
    op.drop_column('user_orders', 'user_id')
    op.drop_column('user_orders', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_orders', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user_orders', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk__user_orders__manager_id__user'), 'user_orders', type_='foreignkey')
    op.create_foreign_key('fk__user_orders__user_id__user', 'user_orders', 'user', ['user_id'], ['chat_id'])
    op.drop_column('user_orders', 'close_date')
    op.drop_column('user_orders', 'manager_id')
    op.add_column('order', sa.Column('time', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('place', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('insurance', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('number_of_person', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('transfer', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('wishes', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('excursion', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('order', 'create_date')
    op.drop_column('order', 'about_order')
    # ### end Alembic commands ###
