"""Username can be null

Revision ID: cbeaa7516401
Revises: 82b9511cb7b8
Create Date: 2022-05-07 22:04:50.991210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbeaa7516401'
down_revision = '82b9511cb7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__order__order_id'), 'order', ['order_id'])
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(op.f('uq__user__chat_id'), 'user', ['chat_id'])
    op.create_unique_constraint(op.f('uq__user_orders__order_id'), 'user_orders', ['order_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__user_orders__order_id'), 'user_orders', type_='unique')
    op.drop_constraint(op.f('uq__user__chat_id'), 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('uq__order__order_id'), 'order', type_='unique')
    # ### end Alembic commands ###
